/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_asuna_miguel_ardon_11311056;

import ReconocimientoVoz.ReconocimientoVoz;
import BaseDatos.Conn;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Miguel A. Ardon E
 */
public class Asuna extends javax.swing.JFrame implements Runnable {

    //public ReconocimientoVoz escuchar;
    public Thread hiloEscucha;
    public ReconocimientoVoz escuchar;
    public String nombre;
    public boolean inicio = false;
    byte accion;

    /**
     * Creates new form Main
     *
     * @param args
     */
    public static void main(String args[]) throws InterruptedException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asuna.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asuna.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asuna.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asuna.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asuna().setVisible(true);
                
            }
        });
    }

    public Asuna() {
        initComponents();
        this.pack();
        this.setSize(650, 530);
        this.setLocationRelativeTo(this);
        this.setVisible(true);

        String cadena;
        FileReader f = null;
        BufferedReader b = null;
        try {
            f = new FileReader("bitacora.txt");
            b = new BufferedReader(f);
            while ((cadena = b.readLine()) != null) {
                bitacora += cadena;
            }
            b.close();
        } catch (IOException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        llamar = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        txt_quien_llamar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Principal = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        txt_accion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_result = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        Llamada = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lb_llamda_foto = new javax.swing.JLabel();
        lb_llamada_numero = new javax.swing.JLabel();
        lb_llamada_nombre = new javax.swing.JLabel();
        lb_duracion = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        VideoLlamada = new javax.swing.JDialog();
        lb_video_nombre = new javax.swing.JLabel();
        lb_video_numero = new javax.swing.JLabel();
        lb_video_duracion = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panel_video = new javax.swing.JPanel();
        Mensaje = new javax.swing.JDialog();
        txt_mensaje_nombre = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_mensaje = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        Contacto = new javax.swing.JDialog();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        lb_foto = new javax.swing.JLabel();
        txt_contacto_nombre = new javax.swing.JTextField();
        txt_contacto_numero = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        editar = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        txt_editar_nombre = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        video = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        txt_quien_video = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        llamar.setTitle("A quien llamar?");
        llamar.setResizable(false);

        jLabel8.setFont(new java.awt.Font("TI-Nspire Sans", 1, 14)); // NOI18N
        jLabel8.setText("A quien desea llamar?");

        txt_quien_llamar.setEditable(false);

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setText("Cancelar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout llamarLayout = new javax.swing.GroupLayout(llamar.getContentPane());
        llamar.getContentPane().setLayout(llamarLayout);
        llamarLayout.setHorizontalGroup(
            llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llamarLayout.createSequentialGroup()
                .addGroup(llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(llamarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(llamarLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton3)))
                .addGap(23, 23, 23)
                .addGroup(llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(txt_quien_llamar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        llamarLayout.setVerticalGroup(
            llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(llamarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_quien_llamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(llamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton8))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        llamar.getAccessibleContext().setAccessibleParent(null);

        Principal.setTitle("Principal");
        Principal.setAlwaysOnTop(true);
        Principal.setBackground(new java.awt.Color(0, 0, 0));
        Principal.setModal(true);

        jLabel5.setFont(new java.awt.Font("AR ESSENCE", 1, 24)); // NOI18N
        jLabel5.setText("Principal");

        txt_accion.setEditable(false);
        txt_accion.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N

        jLabel6.setText("Action");

        jLabel7.setText("Action List");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1.(Buscar) Contacto\n2.(Llamar) Contacto\n3.(Editar) Numero de Contacto\n4.(Mute) Llamada\n5.(Video) Llamada\n6.(Enviar) Mensaje\n7.(Colgar) Llamada/VideoLlamada\n8.(Salir) de la Aplicacion\n");
        jScrollPane1.setViewportView(jTextArea1);

        ta_result.setEditable(false);
        ta_result.setColumns(20);
        ta_result.setRows(5);
        jScrollPane2.setViewportView(ta_result);

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal.getContentPane());
        Principal.getContentPane().setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel6))
                            .addGroup(PrincipalLayout.createSequentialGroup()
                                .addComponent(txt_accion, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel7))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel5)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_accion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(41, 41, 41)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        Llamada.setTitle("Llamada");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lb_llamda_foto.setBackground(new java.awt.Color(102, 102, 102));
        lb_llamda_foto.setForeground(new java.awt.Color(153, 153, 153));
        lb_llamda_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        lb_llamada_numero.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        lb_llamada_numero.setText("numero");

        lb_llamada_nombre.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        lb_llamada_nombre.setText("nombre");

        lb_duracion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lb_duracion.setText("duracion");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/end_call.png"))); // NOI18N
        jLabel13.setToolTipText("End");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mute.png"))); // NOI18N
        jLabel12.setToolTipText("MUTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_llamada_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(lb_llamda_foto))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(lb_llamada_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lb_llamada_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_llamada_numero)
                    .addComponent(lb_duracion))
                .addGap(30, 30, 30)
                .addComponent(lb_llamda_foto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout LlamadaLayout = new javax.swing.GroupLayout(Llamada.getContentPane());
        Llamada.getContentPane().setLayout(LlamadaLayout);
        LlamadaLayout.setHorizontalGroup(
            LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LlamadaLayout.setVerticalGroup(
            LlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VideoLlamada.setTitle("Video Llamada");

        lb_video_nombre.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 18)); // NOI18N
        lb_video_nombre.setText("nombre");

        lb_video_numero.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        lb_video_numero.setText("numero");

        lb_video_duracion.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lb_video_duracion.setText("duracion");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mute.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/end_call.png"))); // NOI18N

        javax.swing.GroupLayout panel_videoLayout = new javax.swing.GroupLayout(panel_video);
        panel_video.setLayout(panel_videoLayout);
        panel_videoLayout.setHorizontalGroup(
            panel_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        panel_videoLayout.setVerticalGroup(
            panel_videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout VideoLlamadaLayout = new javax.swing.GroupLayout(VideoLlamada.getContentPane());
        VideoLlamada.getContentPane().setLayout(VideoLlamadaLayout);
        VideoLlamadaLayout.setHorizontalGroup(
            VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoLlamadaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VideoLlamadaLayout.createSequentialGroup()
                        .addComponent(lb_video_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))
                    .addGroup(VideoLlamadaLayout.createSequentialGroup()
                        .addGroup(VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(VideoLlamadaLayout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))
                            .addGroup(VideoLlamadaLayout.createSequentialGroup()
                                .addComponent(lb_video_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addComponent(lb_video_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(VideoLlamadaLayout.createSequentialGroup()
                .addGroup(VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VideoLlamadaLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel19))
                    .addGroup(VideoLlamadaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(panel_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VideoLlamadaLayout.setVerticalGroup(
            VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VideoLlamadaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lb_video_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_video_numero)
                    .addComponent(lb_video_duracion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(panel_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(VideoLlamadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        Mensaje.setTitle("Mensaje");

        txt_mensaje_nombre.setEditable(false);
        txt_mensaje_nombre.setFont(new java.awt.Font("NSimSun", 0, 24)); // NOI18N
        txt_mensaje_nombre.setText("To");

        txt_mensaje.setColumns(20);
        txt_mensaje.setRows(5);
        jScrollPane3.setViewportView(txt_mensaje);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MensajeLayout = new javax.swing.GroupLayout(Mensaje.getContentPane());
        Mensaje.getContentPane().setLayout(MensajeLayout);
        MensajeLayout.setHorizontalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MensajeLayout.createSequentialGroup()
                        .addComponent(txt_mensaje_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        MensajeLayout.setVerticalGroup(
            MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MensajeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_mensaje_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel20.setText("Contact");

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel21.setText("Name:");

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel22.setText("Phone:");

        jButton5.setText("Ok");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        lb_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N

        jButton11.setText("....");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContactoLayout = new javax.swing.GroupLayout(Contacto.getContentPane());
        Contacto.getContentPane().setLayout(ContactoLayout);
        ContactoLayout.setHorizontalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(106, 106, 106))
            .addGroup(ContactoLayout.createSequentialGroup()
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton11)
                            .addGroup(ContactoLayout.createSequentialGroup()
                                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(18, 18, 18)
                                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_contacto_nombre)
                                    .addComponent(txt_contacto_numero, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))))
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lb_foto))
                    .addGroup(ContactoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel20)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        ContactoLayout.setVerticalGroup(
            ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_foto)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_contacto_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(ContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_contacto_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton5)
                .addGap(42, 42, 42))
        );

        editar.setTitle("Edicion de Contacto");

        jLabel9.setFont(new java.awt.Font("TI-Nspire Sans", 0, 14)); // NOI18N
        jLabel9.setText("A quien va a editar?");

        txt_editar_nombre.setEditable(false);

        jButton9.setText("OK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarLayout = new javax.swing.GroupLayout(editar.getContentPane());
        editar.getContentPane().setLayout(editarLayout);
        editarLayout.setHorizontalGroup(
            editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarLayout.createSequentialGroup()
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton9)
                        .addGap(36, 36, 36)
                        .addComponent(jButton10)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        editarLayout.setVerticalGroup(
            editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(editarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        video.setTitle("A quien video llamar?");
        video.setResizable(false);

        jLabel10.setFont(new java.awt.Font("TI-Nspire Sans", 1, 14)); // NOI18N
        jLabel10.setText("A quien desea Video llamar?");

        txt_quien_video.setEditable(false);

        jButton12.setText("OK");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Cancelar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout videoLayout = new javax.swing.GroupLayout(video.getContentPane());
        video.getContentPane().setLayout(videoLayout);
        videoLayout.setHorizontalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoLayout.createSequentialGroup()
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(videoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel10))
                    .addGroup(videoLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton12)))
                .addGap(23, 23, 23)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton13)
                    .addComponent(txt_quien_video, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        videoLayout.setVerticalGroup(
            videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(videoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_quien_video, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(videoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asuna Voice Rec");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/username.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 260, 162, 25);

        txt_user.setEditable(false);
        txt_user.setToolTipText("User Name ");
        jPanel1.add(txt_user);
        txt_user.setBounds(406, 257, 150, 34);

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/password.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 310, 162, 24);

        txt_pass.setEditable(false);
        txt_pass.setToolTipText("Password");
        jPanel1.add(txt_pass);
        txt_pass.setBounds(406, 309, 150, 34);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/axit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(226, 383, 68, 27);

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/start.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(337, 383, 73, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(456, 383, 122, 29);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.gif"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 60, 597, 251);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.iniciarReconocimieto();
        JOptionPane.showMessageDialog(rootPane, "Gracias por usar el reconcimiento de voz Asuna");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        boolean valid = false;
        Conn cn = new Conn();// Obtiene la conexion
        ResultSet rs = null;
        Statement stmt = null;
        int i = 0;
        /*Fin declaracion de variables*/
        try {
            /*Crear la conexion a la base de datos */
            cn.mkConnRe();
            if (cn == null) {
                JOptionPane.showMessageDialog(rootPane, "Error de Conexion a la Base de Datos ");
            } else {
                stmt = cn.conn.createStatement();
                rs = stmt.executeQuery("select id_usuario, nombre, password \n"
                        + "FROM asuna.usuario c \n"
                        + "where c.nombre = '" + txt_user.getText() + "' and c.password = '" + txt_pass.getText() + "';");
                /*Carga los datos de la base de datos a las propiedades de la clase*/
                while (rs.next()) {
                    u = new Usuario(Integer.parseInt(rs.getString("id_usuario")),
                            rs.getString("nombre"), rs.getString("password"), null);
                    valid = true;
                    i++;
                }
                if (i == 0) {
                    //JOptionPane.showMessageDialog(rootPane, "Error la consulta no devolvio registros");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Bienvenido");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex + "1");
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (stmt != null) {
                    stmt.close();
                }
                if (cn.conn != null) {
                    cn.conn.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e + "2");
            }
        }
        if (valid) {
            Conn cnn = new Conn();// Obtiene la conexion
            ResultSet rss = null;
            Statement stmtt = null;
            i = 0;

            /*Fin declaracion de variables*/
            try {
                /*Crear la conexion a la base de datos */
                cnn.mkConnRe();
                if (cnn == null) {
                    JOptionPane.showMessageDialog(rootPane, "Error de Conexion a la Base de Datos ");
                } else {
                    stmtt = cnn.conn.createStatement();
                    rss = stmtt.executeQuery("select id_contacto, nombre, telefono, foto\n"
                            + "FROM asuna.contacto c \n"
                            + "where c.usuario_id_usuario = '" + u.id + "';");
                    /*Carga los datos de la base de datos a las propiedades de la clase*/
                    while (rss.next()) {
                        int id = Integer.parseInt(rss.getString("id_contacto"));
                        String nombre = rss.getString("nombre");
                        String telefono = rss.getString("telefono");
                        String imagen = rss.getString("foto");
                        c = new Contactos(id, nombre, telefono, imagen);

                        contacts.add(c);
                        i++;
                    }
                    if (i == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Error la consulta no devolvio registros");
                    } else {
                    }
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex + "1");
            } finally {
                try {
                    if (rss != null) {
                        rss.close();
                    }
                    if (stmtt != null) {
                        stmtt.close();
                    }
                    if (cnn.conn != null) {
                        cnn.conn.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(rootPane, e + "2");
                }
            }
            u.setContactos(contacts);
            bitacora += "Hora " + date.toString() + " El usuario " + u.getNombre() + " inicio sesion con la cantidad de usuarios: " + u.getContactos().size() + "\n";
            Principal.pack();
            Principal.setLocationRelativeTo(this);
            Principal.setVisible(true);
            Principal.setModal(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "El usuario o la contraseña estan erroneas");
            txt_user.setText("");
            txt_pass.setText("");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (txt_accion.getText().equals("1.(Buscar) Contacto")) {
            bitacora += "Hora " + date.toString() + " Busca contactos" + "\n";
            for (int i = 0; i < u.getContactos().size(); i++) {
                ta_result.append(u.getContactos().get(i).getNombre() + "\n");
            }
        } else if (txt_accion.getText().equals("2.(Llamar) Contacto")) {
            bitacora += "Hora " + date.toString() + " Llama Contacto" + "\n";
            Principal.setVisible(false);
            llamar.pack();
            llamar.setLocationRelativeTo(this);
            llamar.setVisible(true);
            llamar.setModal(true);
        } else if (txt_accion.getText().equals("3.(Editar) Numero de Contacto")) {
            bitacora += "Hora " + date.toString() + " Edita Contacto" + "\n";
            Principal.setVisible(false);
            editar.pack();
            editar.setLocationRelativeTo(this);
            editar.setVisible(true);
            editar.setModal(true);
        } else if (txt_accion.getText().equals("5.(Video) Llamada")) {
            bitacora += "Hora " + date.toString() + " Video Llamada" + "\n";
            Principal.setVisible(false);
            video.pack();
            video.setLocationRelativeTo(this);
            video.setVisible(true);
            video.setModal(true);
        } else if (txt_accion.getText().equals("6.(Enviar) Mensaje")) {
            bitacora += "Hora " + date.toString() + " Envia Mensaje" + "\n";
            Principal.setVisible(false);
            Mensaje.pack();
            Mensaje.setLocationRelativeTo(this);
            Mensaje.setVisible(true);
            Mensaje.setModal(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < u.getContactos().size(); i++) {
            if (u.getContactos().get(i).getNombre().equalsIgnoreCase(txt_quien_llamar.getText())) {
                lb_llamada_nombre.setText(u.getContactos().get(i).getNombre());
                lb_llamada_numero.setText(u.getContactos().get(i).getNumero());
                if (u.getContactos().get(i).getImagen() != null) {
                    ImageIcon icon = new ImageIcon(u.getContactos().get(i).getImagen());
                    lb_llamda_foto.setIcon(icon);
                } else {
                    ImageIcon icon = new ImageIcon("src/Imagenes/user.png");
                    lb_llamda_foto.setIcon(icon);
                }
            }
        }
        bitacora += "Hora " + date.toString() + " llama a: " + txt_quien_llamar.getText() + "\n";
        txt_quien_llamar.setText("");
        llamar.setVisible(false);
        Llamada.pack();
        Llamada.setLocationRelativeTo(this);
        Llamada.setVisible(true);
        Llamada.setModal(true);
        t = new Tiempo(lb_duracion, this);
        t.start();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        txt_quien_llamar.setText("");
        llamar.setVisible(false);
        Principal.pack();
        Principal.setLocationRelativeTo(this);
        Principal.setVisible(true);
        Principal.setModal(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Conn cn = new Conn();
        try {
            Connection cc = cn.mkConnRe();// Obtiene la conexion
            String sql = "";
            sql = "UPDATE contacto SET nombre=? ,telefono=? ,foto=? WHERE usuario_id_usuario="
                    + u.getId() + " and id_contacto=" + id;
            PreparedStatement pst = cc.prepareStatement(sql);
            pst.setString(1, txt_contacto_nombre.getText());
            pst.setString(2, txt_contacto_numero.getText());
            pst.setString(3, direccion_foto);
            int nu = pst.executeUpdate();
            if (nu > 0) {
                JOptionPane.showMessageDialog(rootPane, "Contacto Actualizado con exito!");
                for (int i = 0; i < u.getContactos().size(); i++) {
                    if (u.getContactos().get(i).getNombre().equalsIgnoreCase(txt_editar_nombre.getText())) {
                        u.getContactos().get(i).setNombre(txt_contacto_nombre.getText());
                        u.getContactos().get(i).setNumero(txt_contacto_numero.getText());
                        u.getContactos().get(i).setImagen(direccion_foto);
                    }
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "No se pudo realizar la coneccion!");
        } catch (Exception ex) {
        }

        bitacora += "Hora: " + date.toString() + " edito a " + txt_editar_nombre.getText() + "\n";
        txt_editar_nombre.setText("");
        Contacto.setVisible(false);
        Principal.pack();
        Principal.setLocationRelativeTo(this);
        Principal.setVisible(true);
        Principal.setModal(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < u.getContactos().size(); i++) {
            if (u.getContactos().get(i).getNombre().equalsIgnoreCase(txt_editar_nombre.getText())) {
                txt_contacto_nombre.setText(u.getContactos().get(i).getNombre());
                txt_contacto_numero.setText(u.getContactos().get(i).getNumero());
                if (u.getContactos().get(i).getImagen() != null) {
                    ImageIcon icon = new ImageIcon(u.getContactos().get(i).getImagen());
                    lb_foto.setIcon(icon);
                    id = u.getContactos().get(i).getId();
                } else {
                    ImageIcon icon = new ImageIcon("src/Imagenes/user.png");
                    lb_foto.setIcon(icon);

                }
            }
        }
        editar.setVisible(false);
        Contacto.pack();
        Contacto.setLocationRelativeTo(this);
        Contacto.setVisible(true);
        Contacto.setModal(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        txt_editar_nombre.setText("");
        editar.setVisible(false);
        Principal.pack();
        Principal.setLocationRelativeTo(this);
        Principal.setVisible(true);
        Principal.setModal(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < u.getContactos().size(); i++) {
            if (u.getContactos().get(i).getNombre().equalsIgnoreCase(txt_quien_video.getText())) {
                lb_video_nombre.setText(u.getContactos().get(i).getNombre());
                lb_video_numero.setText(u.getContactos().get(i).getNumero());
            }
        }
        Webcam webcam = Webcam.getDefault();

        WebcamPanel panel = new WebcamPanel(webcam);
        panel.setFPSDisplayed(true);

        window = new JFrame();
        JPanel hola = new JPanel();
        hola.add(panel);
        hola.setVisible(true);
        window.setUndecorated(true);
        window.setLocation(525, 250);
        window.setAlwaysOnTop(true);
        window.add(hola);
        window.add(panel);
        window.setResizable(true);
        window.pack();
        window.setVisible(true);

        bitacora += "Hora " + date.toString() + " video llamada a: " + txt_quien_video.getText() + "\n";
        txt_quien_video.setText("");
        video.setVisible(false);
        VideoLlamada.pack();
        VideoLlamada.setLocationRelativeTo(this);
        VideoLlamada.setVisible(true);
        VideoLlamada.setModal(true);

        t = new Tiempo(lb_video_duracion, this);
        t.start();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        txt_quien_video.setText("");
        video.setVisible(false);
        Principal.pack();
        Principal.setLocationRelativeTo(this);
        Principal.setVisible(true);
        Principal.setModal(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bitacora += "Hora: " + date.toString() + "Envio mensaje a: " + txt_mensaje_nombre.getText() + " con contenido de: " + txt_mensaje.getText() + "\n";
        JOptionPane.showMessageDialog(rootPane, "Se a enviado correctamente el mensaje!");
        Mensaje.setVisible(false);
        Principal.pack();
        Principal.setLocationRelativeTo(this);
        Principal.setVisible(true);
        Principal.setModal(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        direccion_foto = "src/Imagenes/";
        JFileChooser ima = new JFileChooser();
        ima.setCurrentDirectory(new File("src/Imagenes"));
        ima.setDialogTitle("Foto...");
        if (ima.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            direccion_foto += ima.getName(ima.getSelectedFile());
            ImageIcon icon = new ImageIcon(direccion_foto);
            lb_foto.setIcon(icon);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void iniciarReconocimieto() {
        hiloEscucha = new Thread(escuchar = new ReconocimientoVoz(this));
        hiloEscucha.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDialog Contacto;
    public javax.swing.JDialog Llamada;
    public javax.swing.JDialog Mensaje;
    public javax.swing.JDialog Principal;
    public javax.swing.JDialog VideoLlamada;
    public javax.swing.JDialog editar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lb_duracion;
    public javax.swing.JLabel lb_foto;
    private javax.swing.JLabel lb_llamada_nombre;
    private javax.swing.JLabel lb_llamada_numero;
    public javax.swing.JLabel lb_llamda_foto;
    private javax.swing.JLabel lb_video_duracion;
    private javax.swing.JLabel lb_video_nombre;
    private javax.swing.JLabel lb_video_numero;
    public javax.swing.JDialog llamar;
    private static javax.swing.JPanel panel_video;
    public javax.swing.JTextArea ta_result;
    public javax.swing.JTextField txt_accion;
    public javax.swing.JTextField txt_contacto_nombre;
    public javax.swing.JTextField txt_contacto_numero;
    public javax.swing.JTextField txt_editar_nombre;
    public javax.swing.JTextArea txt_mensaje;
    public javax.swing.JTextField txt_mensaje_nombre;
    public javax.swing.JPasswordField txt_pass;
    public javax.swing.JTextField txt_quien_llamar;
    public javax.swing.JTextField txt_quien_video;
    public javax.swing.JTextField txt_user;
    public javax.swing.JDialog video;
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public Contactos c = new Contactos();
    public ArrayList contacts = new ArrayList();
    public Usuario u = new Usuario();
    public Tiempo t;
    public int id;
    public String direccion_foto = "src/Imagenes/";
    public String bitacora;
    public Date date = new Date();
    public JFrame window;
}
